version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmqctl", "status"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network

  producer:
    build:
      context: ./producer
    container_name: producer
    volumes:
      - "./producer/index.js:/app/index.js"
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "3001:3000"

  consumer:
    build:
      context: ./consumer
    container_name: consumer
    depends_on:
      rabbitmq:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./data:/app/data

networks:
  app-network:
